# Generated by Django 5.1.6 on 2025-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_assigntable_resourcecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotGeneratedCourseTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CourseCode', models.CharField(max_length=20)),
                ('FacultyCode', models.CharField(max_length=20)),
                ('Capacity', models.IntegerField()),
                ('MinPerSession', models.IntegerField()),
                ('Lecturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NotGeneratedResourceTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ResourceCode', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField()),
                ('Lecture', models.CharField(max_length=1)),
                ('Tutorial', models.CharField(max_length=1)),
                ('Lab', models.CharField(max_length=1)),
                ('ETC', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='NotGeneratedTable',
        ),
    ]
