# Generated by Django 5.1.6 on 2025-02-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcourseoffer',
            name='Session',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
