# Generated by Django 5.1.6 on 2025-02-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_childcourseoffer_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourceroom',
            old_name='Clinic',
            new_name='ETC',
        ),
        migrations.RemoveField(
            model_name='resourceroom',
            name='Drawing',
        ),
        migrations.RemoveField(
            model_name='resourceroom',
            name='Group',
        ),
        migrations.RemoveField(
            model_name='resourceroom',
            name='Imus',
        ),
        migrations.RemoveField(
            model_name='resourceroom',
            name='Kitchen',
        ),
        migrations.RemoveField(
            model_name='resourceroom',
            name='PBL',
        ),
    ]
