# Generated by Django 5.1.6 on 2025-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('lecturer', models.CharField(max_length=255)),
                ('assigned_room', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=20)),
                ('group_capacity', models.PositiveIntegerField()),
                ('room_capacity', models.PositiveIntegerField()),
                ('assigned_day', models.CharField(max_length=10)),
                ('assigned_time_slot', models.CharField(max_length=20)),
                ('lecture', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('tutorial', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('lab', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('duration', models.PositiveIntegerField()),
            ],
        ),
    ]
